# Generated by Django 5.0.2 on 2025-09-25 15:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon', models.CharField(help_text='FontAwesome icon class', max_length=50)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='KabaleFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='FontAwesome icon class', max_length=50)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kabale Feature',
                'verbose_name_plural': 'Kabale Features',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ManifestoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(choices=[('graduation-cap', 'Education & Youth'), ('female', 'Women Empowerment'), ('leaf', 'Agriculture'), ('road', 'Infrastructure'), ('chart-line', 'Economic Development'), ('shield-alt', 'Community Security')], max_length=50)),
                ('description', models.TextField()),
                ('points', models.JSONField(default=list, help_text='List of bullet points')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manifesto Item',
                'verbose_name_plural': 'Manifesto Items',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Short description for news preview', max_length=500)),
                ('content', models.TextField(help_text='Full article content')),
                ('category', models.CharField(choices=[('leadership', 'Leadership'), ('politics', 'Politics'), ('campaign', 'Campaign'), ('empowerment', 'Empowerment'), ('youth', 'Youth'), ('clarification', 'Clarification'), ('nrm_event', 'NRM Event'), ('women_empowerment', 'Women Empowerment'), ('youth_development', 'Youth Development')], max_length=50)),
                ('location', models.CharField(default='Kabale District', max_length=100)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('image_alt_text', models.CharField(blank=True, max_length=200)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Aunt Enid Campaign', max_length=100)),
                ('tagline', models.CharField(default='Aspiring Woman Member of Parliament', max_length=200)),
                ('subtitle', models.CharField(default='NRM FLAG BEARER Kabale District 2026-2031', max_length=200)),
                ('hero_description', models.TextField(default='A compassionate leader who empowers, connects, and transforms communities')),
                ('phone', models.CharField(default='+256 705 357 149', max_length=20)),
                ('email', models.EmailField(default='auntenid@kabale2026.com', max_length=254)),
                ('location', models.CharField(default='Kabale District, Uganda', max_length=100)),
                ('whatsapp', models.CharField(default='+256 764 195 740', max_length=20)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(default='https://tiktok.com/@auntenid')),
                ('about_title', models.CharField(default='Who is Aunt Enid?', max_length=100)),
                ('about_subtitle', models.CharField(default='A dedicated community leader with a heart for service and transformation', max_length=200)),
                ('why_running', models.TextField(default='As a woman leader deeply rooted in Kabale District, I believe in the power of inclusive governance...')),
                ('vision', models.TextField(default='I envision a Kabale District where every family thrives...')),
                ('kabale_title', models.CharField(default='Kabale District', max_length=100)),
                ('kabale_subtitle', models.CharField(default='Our beautiful home with unlimited potential', max_length=200)),
                ('kabale_description', models.TextField(default="Kabale, often called the 'Switzerland of Africa'...")),
                ('footer_description', models.TextField(default='Empowering Kabale District through compassionate leadership and inclusive development.')),
                ('copyright_text', models.CharField(default='2025 Aunt Enid Campaign. All rights reserved.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
