# Generated by Django 5.0.2 on 2025-09-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email',
            field=models.EmailField(default='auntenidoa@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='phone',
            field=models.CharField(default='0764195740', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='whatsapp',
            field=models.CharField(default='+256 705 357149', max_length=20),
        ),
    ]
