# Generated by Django 5.0.2 on 2026-06-17 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_siteconfiguration_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Gallery Category',
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional short description of this category')),
                ('icon', models.CharField(default='hands-helping', help_text="FontAwesome icon class e.g. 'hands-helping', 'female', 'seedling', 'heartbeat'", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_part1_text',
            field=models.TextField(default='As a woman leader deeply rooted in Kabale District, I believe in the power of inclusive governance that uplifts every voice, especially those often unheard. Our community deserves leadership that understands the unique challenges we face and has the compassion to address them with wisdom and determination.', help_text='Content for the first About section'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_part1_title',
            field=models.CharField(default="Why I'm Running", help_text='Heading for the first About section', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_part2_text',
            field=models.TextField(default='I envision a Kabale District where every family thrives, where women and youth are empowered, where education is accessible to all, and where our natural resources benefit our entire community. This vision drives my commitment to serve as your representative in Parliament.', help_text='Content for the second About section'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_part2_title',
            field=models.CharField(default='My Vision', help_text='Heading for the second About section', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='vision',
            field=models.TextField(default='I envision a Kabale District where every family thrives...', editable=False),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='why_running',
            field=models.TextField(default='As a woman leader deeply rooted in Kabale District...', editable=False),
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('image', 'Photo'), ('video', 'Video')], default='image', help_text="Select 'Photo' to upload an image, 'Video' to paste a video URL", max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Upload a photo. For videos, upload a thumbnail image here.', null=True, upload_to='gallery/')),
                ('video_url', models.URLField(blank=True, help_text='Paste a YouTube, Vimeo, Facebook or TikTok video URL (only for Video type)')),
                ('caption', models.TextField(blank=True, help_text='Optional caption shown under the media')),
                ('date_taken', models.DateField(blank=True, help_text='Date the photo/video was taken', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on gallery landing page')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Select the gallery category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='website.gallerycategory')),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['-date_taken', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpactProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Short description shown on the listing page', max_length=400)),
                ('description', models.TextField(help_text='Full project description and story')),
                ('image', models.ImageField(blank=True, help_text='Main project photo', null=True, upload_to='impact/')),
                ('location', models.CharField(default='Kabale District', max_length=150)),
                ('date_completed', models.DateField(blank=True, help_text='Leave blank if ongoing', null=True)),
                ('beneficiaries', models.CharField(blank=True, help_text="e.g. '200 women trained'", max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage impact highlights')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Select the category for this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='website.projectcategory')),
            ],
            options={
                'verbose_name': 'Impact Project',
                'verbose_name_plural': 'Impact Projects',
                'ordering': ['-date_completed', '-created_at'],
            },
        ),
    ]
