# Generated by Django 5.0.2 on 2026-06-18 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_gallerycategory_projectcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video directly from your phone or laptop (MP4, MOV, WebM, AVI — max 200 MB). Leave blank if you are using a video link below instead.', null=True, upload_to='gallery/videos/'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='caption',
            field=models.TextField(blank=True, help_text='Optional caption shown under the media.'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select the gallery category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='website.gallerycategory'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='date_taken',
            field=models.DateField(blank=True, help_text='Date the photo/video was taken.', null=True),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo (or a thumbnail for videos uploaded by URL).', null=True, upload_to='gallery/images/'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature on gallery landing page.'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='media_type',
            field=models.CharField(choices=[('image', 'Photo'), ('video', 'Video')], default='image', help_text="Select 'Photo' for an image, 'Video' for a video file or link.", max_length=10),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='video_url',
            field=models.URLField(blank=True, help_text='OR paste a YouTube, Vimeo, TikTok, or Facebook video link. Leave blank if you uploaded a video file above.'),
        ),
    ]
