"""
Django settings for aunt_enid_campaign project.

Generated by 'django-admin startproject' using Django 5.0.2.
"""

import os
import dj_database_url
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY
# Prefer setting DJANGO_SECRET_KEY in environment for production
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-u12@o6uixs=v%&myjo(gcg_ocg(^$q&6dcvwrq8ff3(-bz)@@*"
)

# DEBUG from environment (default True for local/dev). Set to 'False' in production.
DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True"

# Hosts - allow from environment or use defaults
_allowed = os.getenv("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = (
    [h.strip() for h in _allowed.split(",") if h.strip()]
    if _allowed
    else [
        'twiina.com',
        'www.twiina.com',
        'localhost',
        '127.0.0.1',
        '.railway.app',
        '.up.railway.app',
    ]
)

CSRF_TRUSTED_ORIGINS = [
    'http://twiina.com',
    'https://twiina.com',
    'http://www.twiina.com',
    'https://www.twiina.com',
    'http://localhost',
    'https://localhost',
    'https://*.railway.app',
    'https://*.up.railway.app',
]


# Application definition
INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "whitenoise.runserver_nostatic",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "website",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "aunt_enid_campaign.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "website.context_processors.site_config",
            ],
        },
    },
]

WSGI_APPLICATION = "aunt_enid_campaign.wsgi.application"

# Database - use DATABASE_URL (Railway/Heroku) or fall back to sqlite
DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"  # change to 'Africa/Kampala' if you prefer local time
USE_I18N = True
USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ========== Jazzmin Admin Theme ==========
JAZZMIN_SETTINGS = {
    "site_title": "Aunt Enid Admin",
    "site_header": "Enid Asiimwe Campaign",
    "site_brand": "Aunt Enid",
    "site_logo": None,
    "login_logo": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "Welcome to the Enid Asiimwe Campaign Portal",
    "copyright": "Enid Asiimwe for Kabale District",
    "search_model": ["website.NewsArticle", "website.ContactMessage"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home", "url": "/", "new_window": True},
        {"name": "View Site", "url": "/", "new_window": True},
    ],
    "usermenu_links": [
        {"name": "View Site", "url": "/", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "website",
        "website.SiteConfiguration",
        "website.NewsArticle",
        "website.ManifestoItem",
        "website.CoreValue",
        "website.KabaleFeature",
        "website.ContactMessage",
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "website.NewsArticle": "fas fa-newspaper",
        "website.ManifestoItem": "fas fa-scroll",
        "website.ContactMessage": "fas fa-envelope",
        "website.SiteConfiguration": "fas fa-cog",
        "website.CoreValue": "fas fa-star",
        "website.KabaleFeature": "fas fa-map-marker-alt",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-teal",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cosmo",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

# ========== Static & Media Files ==========
# Static served via WhiteNoise
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# ========== Media Storage (local filesystem) ==========
# Served via urls.py (django.conf.urls.static) in both DEBUG and production
# since this project doesn't use S3. Works fine for a small site on Railway.
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"