"""
Django settings for aunt_enid_campaign project.

Generated by 'django-admin startproject' using Django 5.0.2.
"""

import os
import dj_database_url
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY
# Prefer setting DJANGO_SECRET_KEY in environment for production
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-u12@o6uixs=v%&myjo(gcg_ocg(^$q&6dcvwrq8ff3(-bz)@@*"
)

# DEBUG from environment (default True for local/dev). Set to 'False' in production.
DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True"

# Hosts - allow from environment or use defaults
_allowed = os.getenv("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = (
    [h.strip() for h in _allowed.split(",") if h.strip()]
    if _allowed
    else [
        'twiina.com',
        'www.twiina.com',
        'localhost',
        '127.0.0.1',
        '.railway.app',
        '.up.railway.app',
    ]
)

CSRF_TRUSTED_ORIGINS = [
    'http://twiina.com',
    'https://twiina.com',
    'http://www.twiina.com',
    'https://www.twiina.com',
    'http://localhost',
    'https://localhost',
    'https://*.railway.app',
    'https://*.up.railway.app',
]


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "whitenoise.runserver_nostatic",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "website",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "aunt_enid_campaign.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "website.context_processors.site_config",
            ],
        },
    },
]

WSGI_APPLICATION = "aunt_enid_campaign.wsgi.application"

# Database - use DATABASE_URL (Railway/Heroku) or fall back to sqlite
DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"  # change to 'Africa/Kampala' if you prefer local time
USE_I18N = True
USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ========== Static & Media Files ==========
# Static served via WhiteNoise
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ========== Media Storage (local filesystem) ==========
# Served via urls.py (django.conf.urls.static) in both DEBUG and production
# since this project doesn't use S3. Works fine for a small site on Railway.
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"