"""
Django settings for aunt_enid_campaign project.

Generated by 'django-admin startproject' using Django 5.0.2.
"""

import os
import dj_database_url
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY
# Prefer setting DJANGO_SECRET_KEY in environment for production
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-u12@o6uixs=v%&myjo(gcg_ocg(^$q&6dcvwrq8ff3(-bz)@@*"
)

# DEBUG from environment (default True for local/dev). Set to 'False' in production.
DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True"

# Security Proxy Headers for Railway/SSL termination
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Hosts - allow from environment or use defaults (strictly auto-allows all hosts by default)
_allowed = os.getenv("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = (
    [h.strip() for h in _allowed.split(",") if h.strip()]
    if _allowed
    else ['*']
)

# CSRF Trusted Origins - allow from environment or use defaults
_csrf_allowed = os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = (
    [o.strip() for o in _csrf_allowed.split(",") if o.strip()]
    if _csrf_allowed
    else [
        'http://twiina.com',
        'https://twiina.com',
        'http://www.twiina.com',
        'https://www.twiina.com',
        'http://localhost',
        'https://localhost',
        'https://*.railway.app',
        'https://*.up.railway.app',
    ]
)


# Application definition
INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "whitenoise.runserver_nostatic",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "website",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "aunt_enid_campaign.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "website.context_processors.site_config",
            ],
        },
    },
]

WSGI_APPLICATION = "aunt_enid_campaign.wsgi.application"

# Database - use DATABASE_URL (Railway/Heroku), individual Postgres credentials, or fall back to sqlite
DATABASE_URL = os.getenv("DATABASE_URL")

# Auto-scan environment variables for Railway-injected Postgres connection URLs
# (e.g. POSTGRES_PRODUCTION_3638_URL or any other uniquely named service URL)
if not DATABASE_URL:
    for key, value in os.environ.items():
        if (key.endswith("_URL") or "URL" in key) and ("postgres" in value or "postgresql" in value):
            DATABASE_URL = value
            break

DB_NAME = os.getenv("DB_NAME") or os.getenv("PGDATABASE") or os.getenv("POSTGRES_DB")
DB_USER = os.getenv("DB_USER") or os.getenv("PGUSER") or os.getenv("POSTGRES_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD") or os.getenv("PGPASSWORD") or os.getenv("POSTGRES_PASSWORD")
DB_HOST = os.getenv("DB_HOST") or os.getenv("PGHOST") or os.getenv("POSTGRES_HOST")
DB_PORT = os.getenv("DB_PORT") or os.getenv("PGPORT") or os.getenv("POSTGRES_PORT")

# Auto-scan for uniquely-prefixed individual Postgres variables from Railway
if not DATABASE_URL and not DB_NAME:
    for key in os.environ:
        if key.endswith("_HOST") and ("POSTGRES" in key or "DB" in key):
            prefix = key[:-4]  # Extract prefix, e.g., "POSTGRES_PRODUCTION_3638_"
            DB_HOST = os.getenv(prefix + "HOST")
            DB_PORT = os.getenv(prefix + "PORT", "5432")
            DB_NAME = os.getenv(prefix + "DB") or os.getenv(prefix + "DATABASE")
            DB_USER = os.getenv(prefix + "USER")
            DB_PASSWORD = os.getenv(prefix + "PASSWORD") or os.getenv(prefix + "PASS")
            if DB_HOST and DB_NAME and DB_USER and DB_PASSWORD:
                break

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
elif DB_NAME and DB_USER:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD or '',
            'HOST': DB_HOST or 'localhost',
            'PORT': DB_PORT or '5432',
        }
    }
else:
    # If no DATABASE_URL or Postgres credentials are set, but a Railway volume is attached, use SQLite in the volume
    RAILWAY_VOLUME_PATH = os.getenv("RAILWAY_VOLUME_MOUNT_PATH")
    if RAILWAY_VOLUME_PATH:
        db_path = Path(RAILWAY_VOLUME_PATH) / "db.sqlite3"
    else:
        db_path = BASE_DIR / "db.sqlite3"

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': db_path,
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Africa/Kampala"
USE_I18N = True
USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ========== File Upload Limits ==========
# Allow images/videos up to 200 MB (default Django limit is 2.5 MB)
# Videos from phone/laptop can easily be 100-200 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 209_715_200   # 200 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 209_715_200   # 200 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000
# Large uploads go to a temp file instead of memory (efficient for video)
FILE_UPLOAD_TEMP_DIR = None   # uses system temp dir; override with volume path below

# ========== Caching & Performance ==========
# Cache static files aggressively via WhiteNoise (already set in STATICFILES_STORAGE)
# Add a short server-side cache for repeated DB reads on high-traffic pages
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "auntenid-cache",
    }
}

# ========== Jazzmin Admin Theme ==========
JAZZMIN_SETTINGS = {
    "site_title": "Aunt Enid Admin",
    "site_header": "Enid Asiimwe Campaign",
    "site_brand": "Aunt Enid",
    "site_logo": None,
    "login_logo": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "Welcome to the Enid Asiimwe Campaign Portal",
    "copyright": "Enid Asiimwe for Kabale District",
    "search_model": ["website.NewsArticle", "website.ContactMessage"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home", "url": "/", "new_window": True},
        {"name": "View Site", "url": "/", "new_window": True},
    ],
    "usermenu_links": [
        {"name": "View Site", "url": "/", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "website",
        "website.SiteConfiguration",
        "website.NewsArticle",
        "website.ManifestoItem",
        "website.CoreValue",
        "website.KabaleFeature",
        "website.ContactMessage",
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "website.NewsArticle": "fas fa-newspaper",
        "website.ManifestoItem": "fas fa-scroll",
        "website.ContactMessage": "fas fa-envelope",
        "website.SiteConfiguration": "fas fa-cog",
        "website.CoreValue": "fas fa-star",
        "website.KabaleFeature": "fas fa-map-marker-alt",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-teal",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cosmo",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

# ========== Static & Media Files ==========
# Static served via WhiteNoise
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# ========== Media Storage (S3 or local filesystem) ==========
# Detect AWS or S3-compatible credentials (supports custom endpoints like MinIO/Tigris on Railway)
AWS_ACCESS_KEY_ID = (
    os.getenv("AWS_ACCESS_KEY_ID") 
    or os.getenv("S3_ACCESS_KEY") 
    or os.getenv("S3_KEY")
    or os.getenv("MINIO_ROOT_USER")
)
AWS_SECRET_ACCESS_KEY = (
    os.getenv("AWS_SECRET_ACCESS_KEY") 
    or os.getenv("S3_SECRET_KEY") 
    or os.getenv("S3_SECRET")
    or os.getenv("MINIO_ROOT_PASSWORD")
)
AWS_STORAGE_BUCKET_NAME = (
    os.getenv("AWS_STORAGE_BUCKET_NAME") 
    or os.getenv("S3_BUCKET") 
    or os.getenv("S3_BUCKET_NAME") 
    or "auntenid"
)
AWS_S3_ENDPOINT_URL = (
    os.getenv("AWS_S3_ENDPOINT_URL") 
    or os.getenv("S3_ENDPOINT")
)

# For Tigris (t3.storageapi.dev), region must default to "auto" to prevent مالform signature errors
AWS_S3_REGION_NAME = (
    os.getenv("AWS_S3_REGION_NAME") 
    or os.getenv("S3_REGION") 
    or ("auto" if AWS_S3_ENDPOINT_URL and "t3.storageapi.dev" in AWS_S3_ENDPOINT_URL else "eu-north-1")
)

# Force S3v4 signature version (strictly required by Tigris and many modern S3 storage systems)
AWS_S3_SIGNATURE_VERSION = 's3v4'

if AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY:
    # Use S3-compatible storage
    storages_options = {
        "bucket_name": AWS_STORAGE_BUCKET_NAME,
        "querystring_auth": False,
        "file_overwrite": False,
        "location": "media",
    }
    
    if AWS_S3_REGION_NAME:
        storages_options["region_name"] = AWS_S3_REGION_NAME
        
    if AWS_S3_ENDPOINT_URL:
        storages_options["endpoint_url"] = AWS_S3_ENDPOINT_URL
        endpoint_clean = AWS_S3_ENDPOINT_URL.rstrip("/")
        if "t3.storageapi.dev" in endpoint_clean:
            # Tigris virtual-hosted style URL: https://<bucket>.t3.storageapi.dev/media/
            scheme = "https" if endpoint_clean.startswith("https") else "http"
            domain = endpoint_clean.split("://")[-1]
            MEDIA_URL = f"{scheme}://{AWS_STORAGE_BUCKET_NAME}.{domain}/media/"
        else:
            # Path-style fallback for MinIO/other
            MEDIA_URL = f"{endpoint_clean}/{AWS_STORAGE_BUCKET_NAME}/media/"
    else:
        MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/media/"

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": storages_options,
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }
else:
    # Fallback to local filesystem
    MEDIA_URL = "/media/"
    # Check if we are running on Railway with a volume attached
    RAILWAY_VOLUME_PATH = os.getenv("RAILWAY_VOLUME_MOUNT_PATH")
    if RAILWAY_VOLUME_PATH:
        MEDIA_ROOT = Path(RAILWAY_VOLUME_PATH) / "media"
        MEDIA_ROOT.mkdir(parents=True, exist_ok=True)

        # Always copy repo media files to the volume so seeded images are never lost
        # after a redeploy.  User-uploaded files that only exist on the volume
        # (not in the repo) are left untouched because os.walk only visits the repo tree.
        repo_media_dir = BASE_DIR / "media"
        if repo_media_dir.exists() and repo_media_dir != MEDIA_ROOT:
            import shutil
            for root, dirs, files in os.walk(repo_media_dir):
                rel_path = Path(root).relative_to(repo_media_dir)
                dest_dir = MEDIA_ROOT / rel_path
                dest_dir.mkdir(parents=True, exist_ok=True)
                for file in files:
                    src_file = Path(root) / file
                    dest_file = dest_dir / file
                    # Always overwrite repo-tracked files so latest version is used
                    shutil.copy2(src_file, dest_file)
    else:
        MEDIA_ROOT = BASE_DIR / "media"